name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm test
